# Generated by Django 3.2.7 on 2022-01-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20220123_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='noOfAtm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='otherAtmDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
