# Generated by Django 3.1.4 on 2021-09-13 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20210911_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageone',
            options={'verbose_name': 'PageOne', 'verbose_name_plural': 'PageOnes'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='vendors',
        ),
        migrations.AddField(
            model_name='schedule',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.site'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sites',
            field=models.ManyToManyField(blank=True, through='audits.Schedule', to='audits.Site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
