# Generated by Django 3.2.7 on 2022-01-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20220123_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
