# Generated by Django 3.1.4 on 2021-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_auto_20210913_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='pagefour',
            old_name='picture',
            new_name='ER_picture_or_space_to_build',
        ),
        migrations.RemoveField(
            model_name='pagethree',
            name='has_dedicated_transformer',
        ),
        migrations.AddField(
            model_name='pagethree',
            name='details',
            field=models.CharField(default=0, help_text='Enter the number and size of the solar panels.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagethree',
            name='size_of_transformer',
            field=models.IntegerField(help_text='in kVA', null=True),
        ),
        migrations.AlterField(
            model_name='pagefour',
            name='available',
            field=models.BooleanField(default=False, help_text='Only tick if equipment room is available.'),
        ),
        migrations.AlterField(
            model_name='pagefour',
            name='bungalow',
            field=models.BooleanField(default=False, help_text='State the building type and other information as below.'),
        ),
        migrations.AlterField(
            model_name='pagefour',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='State in 24-hours format', null=True),
        ),
        migrations.AlterField(
            model_name='pagefour',
            name='not_available',
            field=models.BooleanField(default=False, help_text='Only tick if equipment room is NOT available.'),
        ),
        migrations.AlterField(
            model_name='pagefour',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='State in 24-hours format', null=True),
        ),
        migrations.AlterField(
            model_name='pageone',
            name='others',
            field=models.CharField(blank=True, help_text='Please state the power rating in Watts.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagesix',
            name='roof_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagethree',
            name='battery_bank_1',
            field=models.CharField(blank=True, help_text='e.g 24 units of 12V 200AH', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagethree',
            name='item1',
            field=models.CharField(blank=True, help_text='State the equipment/appliance name and the rating in kW or kVA in each case. ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagetwo',
            name='others',
            field=models.TextField(blank=True, help_text='Please enter the name and counts of other appliances if exist.', null=True),
        ),
    ]
