# Generated by Django 3.2.7 on 2022-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_auto_20220126_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist2',
            name='roofing_sheet_lapping',
        ),
        migrations.AddField(
            model_name='checklist',
            name='distance_to_roof',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='State the distance from the  ER to the roof'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='roofing_sheet_thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Sheet Thickness (mm)'),
        ),
        migrations.AddField(
            model_name='checklist2',
            name='roofing_sheet_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Sheet Material'),
        ),
        migrations.AddField(
            model_name='checklist2',
            name='roofing_truss_spacing',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Roofing Truss Spacing'),
        ),
        migrations.AddField(
            model_name='checklist3',
            name='breakerSize',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Is there a Spare Breaker at the Injection Point?'),
        ),
        migrations.AddField(
            model_name='checklist3',
            name='distance_to_generator',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='State the distance from the ER to the generator'),
        ),
        migrations.AddField(
            model_name='checklist3',
            name='roofing_truss_spacing',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Roofing Truss Spacing'),
        ),
        migrations.AddField(
            model_name='checklist3',
            name='spareBreaker',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is there a Spare Breaker at the Injection Point?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='Distribution_board_picture',
            field=models.ImageField(blank=True, default='default4.jpg', null=True, upload_to='db_pics', verbose_name='Attach picture of the DB'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='ER_picture_or_space_to_build',
            field=models.ImageField(blank=True, default='default5.jpg', null=True, upload_to='er_pics', verbose_name='Please attach the picture'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='GeneralComment',
            field=models.TextField(blank=True, null=True, verbose_name='General Comments'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='ac_maintenance_avg_cost',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Average Cost on Air Conditioners Maintenance'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='auditDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Audit'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='auditor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Auditor's Name"),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='auditor_phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='battery_bank_1',
            field=models.CharField(blank=True, help_text='e.g 24 units of 12V 200AH', max_length=100, null=True, verbose_name='Battery Bank 1'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='battery_bank_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Bank 2'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='battery_bank_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Bank 3'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='battery_bank_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Battery Bank 4'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='card_printer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Card Printer'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='changeover_box_picture',
            field=models.ImageField(blank=True, default='default3.jpg', null=True, upload_to='changeover_pics', verbose_name='Attach picture of the Changeover Box'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='client_rep',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Customer Representative's Name"),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='client_repPhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='complete_replacement',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Complete Replacement'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='connects_to_generator',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Connects to Generator?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='connects_to_grid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the conneted to the Grid?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='connects_to_solar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Connects to Solar?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='contact_personPhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='diesel_avg_cost',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Monthly Average Cost on Diesel'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='dimension',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='What is the dimension of the room or space?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='distance_to_generator',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='State the distance from the ER to the generator'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='distance_to_powerRoom',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='State the distance from the  ER to the existing Power Room'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='eight',
            field=models.ImageField(blank=True, default='default6.jpg', null=True, upload_to='safety', verbose_name='Attach the picture'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='energy_saver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Energy Saver Bulb'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='er_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Equipment Room Available?'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='general_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='gensets_maintenance_avg_cost',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Average Cost on Generator Maintenance'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='grid_avg_cost',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Monthly Average Cost on Grid'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='hand_dryer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hand Dryer'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='major_repair',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Major Repair'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='mantrap_door',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mantrap Door'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='minor_repair',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Minor Repair'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='multi_commercial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Multi-Commercial'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='multi_resident',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Multi-Resident'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='noOfAtm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of ATMs'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='on_what_floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='On what floor is the ER or the available space'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='one_storey',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='One Storey'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='otherAtmDetails',
            field=models.TextField(blank=True, null=True, verbose_name='Other Details'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='other_appliances',
            field=models.TextField(blank=True, help_text='Please enter the name and counts of other appliances if exist.', null=True, verbose_name='Other Appliances'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='other_cost',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Other Associated Cost'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='other_lights',
            field=models.CharField(blank=True, help_text='Please state the power rating in Watts.', max_length=50, null=True, verbose_name='Other Light Bulbs'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='panel_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Panel Light'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='repair_needed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does the roof requires repair'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roof_length',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Roof Length'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roof_picture',
            field=models.ImageField(blank=True, default='default2.jpg', null=True, upload_to='roof_pics', verbose_name='Roof Picture'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roof_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roof Type'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roof_width',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Roof Width'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roofing_sheet_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Sheet Material'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roofing_truss_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Truss Material'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='roofing_truss_spacing',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Roofing Truss Spacing'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='site_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sorting_machine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sorting Machine'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='space_toBuild',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='If not, is there space to build one? '),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='three_storey',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Three Storey'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='time_stamping_machine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Timestamping Machine'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='total_area',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Number of Panels'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='two_storey',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Two Storey'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='Distribution_board_picture',
            field=models.ImageField(blank=True, default='default5.jpg', null=True, upload_to='db_pics', verbose_name='Attach picture of the DB'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='ER_picture_or_space_to_build',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='er_pics', verbose_name='Please attach the picture'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='GeneralComment',
            field=models.TextField(blank=True, null=True, verbose_name='General Comments'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='ago_pump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number and Size(in HP) of AGO Pumps'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='auditDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Audit'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='auditor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Auditor's Name"),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='auditor_phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='building_picture',
            field=models.ImageField(default='default2.jpg', upload_to='building_pics', verbose_name='Attach picture of the building'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='building_type',
            field=models.CharField(default=False, help_text='State the building type and other information as below.', max_length=100, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='changeover_box_picture',
            field=models.ImageField(blank=True, default='default4.jpg', null=True, upload_to='changeover_pics', verbose_name='Attach picture of the Changeover Box'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='client_rep',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Customer Representative's Name"),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='client_repPhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='contact_personPhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='dpk_pump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number and Size(in HP) of DPK Pumps'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='eight',
            field=models.ImageField(blank=True, default='default6.jpg', null=True, upload_to='safety', verbose_name='Attach the picture'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='energy_saver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Energy Saver Bulb'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='generator_1',
            field=models.CharField(blank=True, help_text='in kVA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='note_counting_machine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note Counting Machine'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='other_lights',
            field=models.CharField(blank=True, help_text='Please state the power rating in Watts.', max_length=50, null=True, verbose_name='Other Light Bulbs'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='others_equipment',
            field=models.TextField(verbose_name='Other Equipment'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='panel_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Panel Light'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='pms_pump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number and Size(in HP) of PMS Pumps'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='roof_material',
            field=models.CharField(blank=True, help_text='Concrete slab, Aluminum, Ardex, Specify if others', max_length=30, null=True, verbose_name='Roof Material'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='roof_picture',
            field=models.ImageField(blank=True, default='default3.jpg', null=True, upload_to='roof_pics', verbose_name='Roof Picture'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='roof_type',
            field=models.CharField(blank=True, help_text='Flat, Mono-Pitch, Double-Pitch, Specify if others', max_length=200, null=True, verbose_name='Roof Type'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='roofing_sheet_thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Sheet Thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='roofing_truss_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Truss Material'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='site_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='size',
            field=models.CharField(blank=True, help_text='State the size of te three pahse equipment (in HP)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='surface_transfer_pump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size (in HP) of the surface pumps'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='three_phase_equipment',
            field=models.BooleanField(verbose_name='I there any 3- Phase Equipment?'),
        ),
        migrations.AlterField(
            model_name='checklist2',
            name='water_pump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Water Pumps'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='ER_picture_or_space_to_build',
            field=models.ImageField(default='default3.jpg', upload_to='er_pics', verbose_name='Please attach the picture'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='ER_to_power_room_distance',
            field=models.IntegerField(blank=True, help_text='meters', null=True, verbose_name='State the distance from the  ER to the existing Power Room'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='GeneralComment',
            field=models.TextField(blank=True, null=True, verbose_name='General Comments'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='auditDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Audit'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='auditor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Auditor's Name"),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='auditor_phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='availability_of_synchPanel',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is there a Synchronization Panel?'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='average_dayLoad',
            field=models.CharField(blank=True, help_text='kW', max_length=30, null=True, verbose_name='Average Load'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='average_nightLoad',
            field=models.CharField(blank=True, help_text='kW', max_length=30, null=True, verbose_name='Average Night Load'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='backupSize',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True, verbose_name='Size of Critical Load (kW)'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='building_type',
            field=models.CharField(default=False, help_text='State the building type and other information as below.', max_length=100, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='client_rep',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Customer Representative's Name"),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='client_repPhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='connects_to_grid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is the Facility conneted to the Grid?'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='contact_personPhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='daily_consumption',
            field=models.CharField(blank=True, help_text='kWh', max_length=30, null=True, verbose_name='Average Daily Energy Consumption'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='equipment_room_availability',
            field=models.BooleanField(verbose_name='Is Equipment Room Available?'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='grid_availability',
            field=models.IntegerField(blank=True, help_text='How many hours out of 24 do you get on an average?', null=True, verbose_name='Grid Availability'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='grid_quality',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Grid Quality'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='ground_space_1',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Ground Space 1'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='ground_space_2',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Ground Space 2'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='ground_space_picture',
            field=models.ImageField(default='default2.jpg', upload_to='gs_pics', verbose_name='Attach picture of the Ground Space'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='maximum_load',
            field=models.CharField(blank=True, help_text='kW', max_length=30, null=True, verbose_name='Maximum Load'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='minimum_load',
            field=models.CharField(blank=True, help_text='kW', max_length=30, null=True, verbose_name='Minimum Load'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='panel_room_picture',
            field=models.ImageField(default='default4.jpg', upload_to='pr_pics', verbose_name='Existing Power Room Picture'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roof_picture',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='roof_pics', verbose_name='Roof Picture'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roof_space_1',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Roof Space 1'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roof_space_2',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Roof Space 2'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roof_space_3',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Roof Space 3'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roof_space_4',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Roof Space 4'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roof_to_ER_distance',
            field=models.IntegerField(blank=True, help_text='meters', null=True, verbose_name='State the distance from the  ER to the roof'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roofing_sheet_thickness',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Sheet Thickness (mm)'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='roofing_truss_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Roofing Truss Material'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='site_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='size_of_equipment_room',
            field=models.IntegerField(blank=True, help_text='square meters', null=True, verbose_name='Size of Equipment Room'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='switching_mode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Whta is the mode of Switching Power?'),
        ),
        migrations.AlterField(
            model_name='checklist3',
            name='synchPanelSize',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What Voltage Level is the Panel?'),
        ),
    ]
