# Generated by Django 3.1.4 on 2021-09-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auto_20210914_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist',
            new_name='ChecklistForBank',
        ),
        migrations.RenameModel(
            old_name='ChecklistThree',
            new_name='ChecklistForCandI',
        ),
        migrations.RenameModel(
            old_name='ChecklistTwo',
            new_name='ChecklistForFillingStation',
        ),
    ]
